### ISSUE TITLE
Crie um arquivo Readme.md

### ISSUE THREAD

**Issue by Augustocoder** [suemoron/Formulario-responsivo#1]
Com o arquivo "Readme.md "você explica basicamente como funciona o seu projeto e deixa mais claro para a empresa ou o desenvolvedor que está olhando.

**Comment by suemoron** [comment]
Muito obrigada pela dica

**Comment by suemoron** [comment]
> Com o arquivo "Readme.md "você explica basicamente como funciona o seu projeto e deixa mais claro para a empresa ou o desenvolvedor que está olhando.

Muito obrigada pela dica
